url: https://investwellarchitects.com

gems: ['kramdown']
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile']

# Site settings
title: "InvestWell Architects, LLC"
email: angelica.batac@gmail.com
description: "At InvestWell Architects you will receive the attention of a small firm with the experience, expertise and know how of a well established firm. We are here to serve you and to make your investments well worth the commitment."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 13ACA5
  secondary: 15EFE5
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Angelica Batac
  pic: angie_pic1
  position: Registered Architect
  organizations: AIA, NCARB
# social:
    # - title: facebook
      # url: https://www.facebook.com/angelica.u.batac/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# social:
  # - title: twitter
    # url: http://twitter.com/jekyllrb
  # - title: facebook
    # url:
  # - title: stack-overflow
    # url: http://stackoverflow.com/questions/tagged/jekyll
  # - title: bitbucket
    # url: http://bitbucket.org/jekyll
  # - title: github
    # url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
